language: scala

# only trigger builds on master
branches:
  only:
    - master

# start the couchdb service (runs in admin party)
services: couchdb

# create an admin user
before_script:
  - curl -X PUT -d '"admin"' localhost:5984/_config/admins/admin
# optional: create a user document...  - curl -X PUT -d '{ "_id": "org.couchdb.user:admin", "password": null, "name": "admin", "roles": [], "type": "user" }' localhost:5984/_users/org.couchdb.user:admin
